apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "girc.fullname" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  planName: {{ .Values.planName | quote }}
  {{- if .Values.additionalData }}
  additionalData: {{ .Values.additionalData | quote }}
  {{- end }}