apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "girc.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ template "girc.fullname" . }}
    spec:
      containers:
      - name: girc
        image: "tehcyx/girc:latest"
        ports:
            - containerPort: 6665
