apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "girc.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ template "girc.fullname" . }}
    spec:
      containers:
      - name: girc
        image: "docker.pkg.github.com/tehcyx/girc/app:d8e3e6718e6960aa5a5e4201b2144a23fa84fdd3"