apiVersion: v1
kind: Service
metadata:
  name: {{ template "girc.fullname" . }}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "girc.fullname" . }}
  ports:
  - protocol: TCP
    port: 6665
    targetPort: 6665